exports.properties = [
    {
        id: 1,
        title: "The Batsonaa Condo",
        type: "house",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum sed eos minima cumque suscipit. Non fuga est animi incidunt molestiae soluta nostrum delectus veritatis illum.",
        price: "500,000",
        currency: "GHC",
        negotiable: false,
        bedrooms: 3,
        baths: 2,
        area: 200,
        areaUnit: "sqft",
        location: "Batsonaa",
        country: "Ghana",
        region: "Greater Accra",
        company: "Shelter Mart",
        companyLogo: "http://sheltermartgh.com/storage/biggershelter.png",
        verified: true,
        thumbnailUrl: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=600",
        otherImages: [
            "imgUrl_1", 
            "imgUrl_2", 
            "imgUrl_3", 
            "imgUrl_4", 
            "imgUrl_5"
        ],
        available: true,
    },
    {
        id: 2,
        title: "The Batsonaa Condo",
        type: "house",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum sed eos minima cumque suscipit. Non fuga est animi incidunt molestiae soluta nostrum delectus veritatis illum.",
        price: "150,000",
        currency: "USD",
        negotiable: false,
        bedrooms: 3,
        baths: 2,
        area: 200,
        areaUnit: "sqft",
        location: "Batsonaa",
        country: "Ghana",
        region: "Greater Accra",
        company: "Shelter Mart",
        companyLogo: "http://sheltermartgh.com/storage/biggershelter.png",
        verified: true,
        thumbnailUrl: "https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg?auto=compress&cs=tinysrgb&w=600",
        otherImages: [
            "imgUrl_1", 
            "imgUrl_2", 
            "imgUrl_3", 
            "imgUrl_4", 
            "imgUrl_5"
        ],
        available: true,
    },
    {
        id: 3,
        title: "The Batsonaa Condo",
        type: "house",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum sed eos minima cumque suscipit. Non fuga est animi incidunt molestiae soluta nostrum delectus veritatis illum.",
        price: "550,000",
        currency: "USD",
        negotiable: false,
        bedrooms: 5,
        baths: 5,
        area: 500,
        areaUnit: "sqft",
        location: "Batsonaa",
        country: "Ghana",
        region: "Greater Accra",
        company: "Shelter Mart",
        companyLogo: "http://sheltermartgh.com/storage/biggershelter.png",
        verified: true,
        thumbnailUrl: "https://media.istockphoto.com/id/1165384568/photo/europe-modern-complex-of-residential-buildings.jpg?b=1&s=612x612&w=0&k=20&c=t3YaLHuqKH9KIAWMjzkFT78-dLFg4gvtVr5ilBvMphI=",
        otherImages: [
            "imgUrl_1", 
            "imgUrl_2", 
            "imgUrl_3", 
            "imgUrl_4", 
            "imgUrl_5"
        ],
        available: true,
    },
    {
        id: 4,
        title: "The Batsonaa Condo",
        type: "house",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum sed eos minima cumque suscipit. Non fuga est animi incidunt molestiae soluta nostrum delectus veritatis illum.",
        price: "200,000",
        currency: "USD",
        negotiable: false,
        bedrooms: 2,
        baths: 2,
        area: 200,
        areaUnit: "sqft",
        location: "Batsonaa",
        country: "Ghana",
        region: "Greater Accra",
        company: "Shelter Mart",
        companyLogo: "http://sheltermartgh.com/storage/biggershelter.png",
        verified: true,
        thumbnailUrl: "https://images.pexels.com/photos/323776/pexels-photo-323776.jpeg?auto=compress&cs=tinysrgb&w=600",
        otherImages: [
            "imgUrl_1", 
            "imgUrl_2", 
            "imgUrl_3", 
            "imgUrl_4", 
            "imgUrl_5"
        ],
        available: true,
    },
    {
        id: 5,
        title: "The Batsonaa Condo",
        type: "house",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum sed eos minima cumque suscipit. Non fuga est animi incidunt molestiae soluta nostrum delectus veritatis illum.",
        price: "90,000",
        currency: "USD",
        negotiable: false,
        bedrooms: 1,
        baths: 1,
        area: 100,
        areaUnit: "sqft",
        location: "Batsonaa",
        country: "Ghana",
        region: "Greater Accra",
        company: "Shelter Mart",
        companyLogo: "http://sheltermartgh.com/storage/biggershelter.png",
        verified: true,
        thumbnailUrl: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=600",
        otherImages: [
            "imgUrl_1", 
            "imgUrl_2", 
            "imgUrl_3", 
            "imgUrl_4", 
            "imgUrl_5"
        ],
        available: true,
    },
    {
        id: 6,
        title: "The Batsonaa Condo",
        type: "house",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum sed eos minima cumque suscipit. Non fuga est animi incidunt molestiae soluta nostrum delectus veritatis illum.",
        price: "150,000",
        currency: "USD",
        negotiable: false,
        bedrooms: 3,
        baths: 2,
        area: 200,
        areaUnit: "sqft",
        location: "Batsonaa",
        country: "Ghana",
        region: "Greater Accra",
        company: "Shelter Mart",
        companyLogo: "http://sheltermartgh.com/storage/biggershelter.png",
        verified: true,
        thumbnailUrl: "https://images.pexels.com/photos/584399/living-room-couch-interior-room-584399.jpeg?auto=compress&cs=tinysrgb&w=600",
        otherImages: [
            "imgUrl_1", 
            "imgUrl_2", 
            "imgUrl_3", 
            "imgUrl_4", 
            "imgUrl_5"
        ],
        available: true,
    },
    {
        id: 7,
        title: "The Batsonaa Condo",
        type: "house",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum sed eos minima cumque suscipit. Non fuga est animi incidunt molestiae soluta nostrum delectus veritatis illum.",
        price: "150,000",
        currency: "USD",
        negotiable: false,
        bedrooms: 3,
        baths: 2,
        area: 200,
        areaUnit: "sqft",
        location: "Batsonaa",
        country: "Ghana",
        region: "Greater Accra",
        company: "Shelter Mart",
        companyLogo: "http://sheltermartgh.com/storage/biggershelter.png",
        verified: true,
        thumbnailUrl: "https://images.pexels.com/photos/323781/pexels-photo-323781.jpeg?auto=compress&cs=tinysrgb&w=600",
        otherImages: [
            "imgUrl_1", 
            "imgUrl_2", 
            "imgUrl_3", 
            "imgUrl_4", 
            "imgUrl_5"
        ],
        available: true,
    },
    {
        id: 8,
        title: "The Batsonaa Condo",
        type: "house",
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum sed eos minima cumque suscipit. Non fuga est animi incidunt molestiae soluta nostrum delectus veritatis illum.",
        price: "150,000",
        currency: "USD",
        negotiable: false,
        bedrooms: 3,
        baths: 2,
        area: 200,
        areaUnit: "sqft",
        location: "Batsonaa",
        country: "Ghana",
        region: "Greater Accra",
        company: "Shelter Mart",
        companyLogo: "http://sheltermartgh.com/storage/biggershelter.png",
        verified: true,
        thumbnailUrl: "https://images.pexels.com/photos/2961944/pexels-photo-2961944.jpeg?auto=compress&cs=tinysrgb&w=600",
        otherImages: [
            "imgUrl_1", 
            "imgUrl_2", 
            "imgUrl_3", 
            "imgUrl_4", 
            "imgUrl_5"
        ],
        available: true,
    },
];

exports.companies = [
    {
        id: 100,
        name: "Shelter Mart",
        location: "Spintex",
        about: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolorum sed eos minima cumque suscipit. Non fuga est animi incidunt molestiae soluta nostrum delectus veritatis illum.",
        verified: true,
        companyLogo: "http://sheltermartgh.com/storage/biggershelter.png",
    },
];
